### ISSUE TITLE
Weston drm-backend ili9341

### ISSUE THREAD

**Issue by ihora** [notro/tinydrm#16]
Dear sir,
I am happily using Weston on ili9341.
Weston runs on fbdev-backend but I would like to try drm-backend in order to have hardware acceleration.
I encountered tinydrm and realized that it could suit my purpose.
Anyway,so far I have this line in my config.txt on Raspberry Pi:
dtoverlay=rpi-display with couple of other parameters like speed etc.
I would like to kindly ask you,how do I enable tinydrm layer?
Do I have to change config.txt,or should I tun the module automatically?
I still see fbtft as well as fb_ili9341 modules loaded instead of tinydrm module.
I have kernel 4.19.42 and I see some overlays and files related to tinydrm,but I have not found any information how to activate it.
Thank you for your help

**Comment by notro** [comment]
I use this overlay: https://github.com/notro/tinydrm/blob/master/rpi-overlays/rpi-display-overlay.dts
The driver is already enabled in Raspbian: ```CONFIG_TINYDRM_MI0283QT=m```

@anholt has added support to Mesa to enable rendering on vc4 and scanout on mi0283qt: https://gitlab.freedesktop.org/mesa/mesa/commit/8cfc17bdda31a381bfbaadc75f0d34dada0e8c91

I haven't used it myself and have never built Mesa so can't help you getting this to work. Please consider adding a howto wiki page if you get this working.

The ili9341 tinydrm driver doesn't support rpi-display, mi0283qt was the first one added before it was decided to have one driver per controller instead of one driver per panel (family).
